name: Build At
on:
  push:
    branches: [master]
  pull_request:

jobs:
  auth-build:
    name: "Build At"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build
        run: deno task build
